Examples
COMPASS-DOE/whattheflux pull request #50
Opened 2024-03-27 10:46 UTC by wilsonsj100

Adding examples for whattheflux package.

2024-03-27 13:23 UTC, bpbond requested changes
A few changes and all tests are failing. I would suggest make a single directory `examples/` and then put the CH4 and N2O folders within that.

2024-03-27 13:23 UTC, bpbond commented on CH4 Example/Tree_CH4_Uptake_Example.R
> +setwd("S:/Biogeochemistry/People/Wilson (Steph)/Manuscripts/Whattheflux Tech Note/Tree CH4 Uptake Example")
@wilsonsj100 Remove this -- it's only valid for your machine

2024-03-27 13:23 UTC, bpbond commented on CH4 Example/READ ME
Please rename to `README.md` to follow package conventions

2024-03-28 09:36 UTC, wilsonsj100 commented
I just deleted both the folders I made for now.

2024-03-30 09:33 UTC, bpbond commented
Let's come back to this!

2024-03-30 09:33 UTC, closed without merging